# Generated by Django 4.1.7 on 2023-03-01 16:46

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255, unique=True, verbose_name='Familiya Ism Sharif')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='UZ')),
                ('amount', models.PositiveBigIntegerField(verbose_name="To'lov Summasi")),
                ('company', models.CharField(blank=True, max_length=255, verbose_name='Tashkilot Nomi')),
                ('status', models.CharField(choices=[('Yangi', 'Yangi'), ('Moderiyatsada', 'Moderiyatsada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], max_length=255, verbose_name='Holati')),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['fish'],
            },
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('INHA', 'Inha University in Tashkent'), ('WIUT', 'Westminster University in Tashkent'), ('MDIST', 'Management Development Institute of Singapore in Tashkent'), ('AMITY', 'Amity Univesity in Tashkent'), ('AKFA', 'Akfa University in Tashkent')], max_length=255, unique=True, verbose_name='OTM')),
            ],
            options={
                'verbose_name_plural': 'Universities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(max_length=255, unique=True, verbose_name='Familiya Ism Sharif')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='UZ')),
                ('degree', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Phd', 'PhD')], max_length=255, verbose_name='Talabalik Turi')),
                ('year', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], max_length=255, verbose_name='Kurs')),
                ('tuition', models.PositiveBigIntegerField(verbose_name='Kontrakt Miqdori')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='api.university')),
            ],
            options={
                'ordering': ['fish'],
                'unique_together': {('fish', 'university', 'degree')},
            },
        ),
    ]
