# Generated by Django 4.1.7 on 2023-03-01 16:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='UZ', verbose_name='Telefon Raqami'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=15, region='UZ', verbose_name='Telefon Raqami'),
        ),
    ]
