# Generated by Django 4.1.7 on 2023-03-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_sponsor_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('Birinchi', 'Birinchi'), ('Ikkinchi', 'Ikkinchi'), ('Uchinchi', 'Uchinchi'), ("To'rtinchi", "To'rtinchi")], max_length=255, verbose_name='Kurs'),
        ),
    ]
