# Generated by Django 4.1.7 on 2023-03-01 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_sponsorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsorship',
            name='amount',
            field=models.PositiveBigIntegerField(verbose_name="To'lov Summasi"),
        ),
    ]
