# Generated by Django 4.1.7 on 2023-03-02 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_sponsorship_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsorship',
            options={},
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='sponsorship',
            name='student',
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveBigIntegerField(verbose_name="To'lov Summasi")),
                ('date_created', models.DateField(auto_now_add=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='api.sponsor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorship', to='api.student')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
