# Generated by Django 4.1.7 on 2023-03-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_sponsorship_options_remove_sponsorship_amount_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sponsorship',
        ),
    ]
