# Generated by Django 4.1.7 on 2023-03-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_delete_sponsorship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['id'], 'verbose_name_plural': 'Universities'},
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderiyatsada', 'Moderiyatsada'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=255, verbose_name='Holati'),
        ),
    ]
