# Generated by Django 4.1.7 on 2023-03-05 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_donation_options_alter_sponsor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sponsor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name_plural': 'Universities'},
        ),
    ]
